---
agnosticd_foundation: ec2_cloud_formation
agnosticd_architecture: ocp4_cluster
guid: test
uuid: 92dbe315-3d6c-42a2-a452-0c4939426363

aws_region: us-west-2
aws_access_key_id: ...
aws_secret_access_key: ...
