---
roles:
- name: ftl-injector
  src: https://github.com/redhat-gpte-devopsautomation/ftl-injector
  version: v0.17

collections:
- name: community.general
  version: 4.6.1
- name: ansible.posix
  version: 1.3.0

