---
- name: Check required variables are set
  assert:
    that:
    - guid is defined
    - uuid is defined
    - agnosticd_foundation is defined or agnosticd_architecture is defined or agnosticd_implementation is defined
    fail_msg: Required variable not set
  run_once: true
  delegate_to: localhost
