---
- name: Validate foundation vars
  ansible.builtin.include_role:
    name: "foundations/{{ agnosticd_foundation }}"
    public: true
    tasks_from: validate_vars.yml
  when:
  - query('first_found', ['roles/foundations/' ~ agnosticd_foundation ~ '/tasks/validate_vars.yml'], skip=true) | length > 0

- name: Validate architecture vars
  ansible.builtin.include_role:
    name: "architectures/{{ agnosticd_architecture }}"
    public: true
    tasks_from: validate_vars.yml
  when:
  - agnosticd_architecture is defined
  - query('first_found', ['roles/architectures/' ~ agnosticd_architecture ~ '/tasks/validate_vars.yml'], skip=true) | length > 0

- name: Validate workload vars
  loop: "{{ agnosticd_workloads }}"
  loop_control:
    loop_var: __agnosticd_workload
  ansible.builtin.include_role:
    name: "workloads/{{ __agnosticd_workload.name }}"
    tasks_from: validate_vars.yml
  when:
  - query('first_found', ['roles/workloads/' ~ __agnosticd_workload.name ~ '/tasks/validate_vars.yml'], skip=true) | length > 0
