ansible-navigator:
  execution-environment:
    image: quay.io/agnosticd/ee-multicloud:v0.0.6
    #image: ee-multicloud-public:v0.0.6
    #image: quay.io/agnosticd/ee-legacy:ansible2.9-python3.6-2021-11-30
    #image: quay.io/agnosticd/ee-legacy:equinix_metal-ansible2.9-python3.6-2021-11-03
    #image: image-registry.apps.open.redhat.com/agnosticd/ee-multicloud:v0.0.6
    volume-mounts:
      - src: /home/fridim/vars
        dest: /vars
      - src: /home/fridim/secrets
        dest: /secrets
      - src: /tmp
        dest: /tmp

  mode: interactive
