---
- name: AgnosticD Foundation
  gather_facts: false
  hosts: localhost
  vars:
    agnosticd_action: provision
  roles:
  - role: agnosticd_util
  - role: agnosticd_vars
  - role: agnosticd_init
  tasks:
  - name: Foundation Provision
    ansible.builtin.include_role:
      name: "foundations/{{ agnosticd_foundation }}"
      tasks_from: provision.yml

- name: AgnosticD Architecture and Implementation
  gather_facts: false
  hosts: all
  roles:
  - role: agnosticd_util
  - role: agnosticd_vars
  tasks:
  - name: Architecture Provision
    ansible.builtin.include_role:
      name: "architectures/{{ agnosticd_architecture }}"
      tasks_from: provision.yml

  - name: Architecture Workloads
    loop: "{{ agnosticd_workloads }}"
    loop_control:
      loop_var: __agnosticd_workload
    ansible.builtin.include_role:
      name: "workloads/{{ __agnosticd_workload.name }}"
      tasks_from: provision.yml

  - name: AgnosticD Post
    ansible.builtin.include_role:
      name: agnosticd_post
      apply:
        delegate_to: localhost
        delegate_facts: true
        run_once: true
