---
- name: AgnosticD Foundation
  gather_facts: false
  hosts: localhost
  vars:
    agnosticd_action: status
  roles:
  - role: agnosticd_vars
  - role: agnosticd_init
  tasks:
  - name: Foundation Inventory
    ansible.builtin.include_role:
      name: "foundations/{{ agnosticd_foundation }}"
      tasks_from: inventory.yml

  - name: Foundation Status
    ansible.builtin.include_role:
      name: "foundations/{{ agnosticd_foundation }}"
      tasks_from: status.yml
    when:
    - query('first_found', ['roles/foundations/' ~ agnosticd_foundation ~ '/tasks/status.yml'], skip=true) | length > 0

- name: AgnosticD Architecture and Implementation
  gather_facts: false
  hosts: all
  vars:
    agnosticd_action: status
  roles:
  - role: agnosticd_vars
  tasks:
  - name: Architecture Status
    ansible.builtin.include_role:
      name: "architectures/{{ agnosticd_architecture }}"
      tasks_from: status.yml
    when:
    - agnosticd_architecture is defined
    - query('first_found', ['roles/architectures/' ~ agnosticd_architecture ~ '/tasks/status.yml'], skip=true) | length > 0

  - name: Architecture Workloads Status
    loop: "{{ agnosticd_workloads }}"
    loop_control:
      loop_var: __agnosticd_workload
    ansible.builtin.include_role:
      name: "workloads/{{ __agnosticd_workload.name }}"
      tasks_from: status.yml
    when:
    - query('first_found', ['roles/workloads/' ~ __agnosticd_workload.name ~ '/tasks/status.yml'], skip=true) | length > 0

  - name: AgnosticD Post
    ansible.builtin.include_role:
      name: agnosticd_post
      apply:
        delegate_to: localhost
        delegate_facts: true
        run_once: true
