---
# TIP: CHANGEME needs to be adapted once for each developer, CHANGEME-ec2 needs to be adapted for each AWS sandbox
cloudformation_retries: 0

# ## Environment size
#tower_instance_count: 3
#support_instance_count: 5 # 1 DB, 2 normal nodes, 2 isolated nodes
#tower_instance_type: "t2.medium"
#support_instance_type: "t2.medium"
root_filesystem_size: 20                #Size of the root filesystem

# Env config basics
env_type: ansible-automation-platform          # Name of config to deploy
output_dir: /var/tmp/{{ env_type }}_workdir    # Writable working scratch directory
email: jsmith@example.com                      # User info for notifications CHANGEME

# AWS specific
guid: whateverunique                           # A short unique enough identifier CHANGEME
subdomain_base_suffix: .sandboxNNN.example.com  # Your domain used in FQDN CHANGEME-ec2
# Note: the Tower ELB answers under tower.{{ guid }}{{ subdomain_base_suffix }}

# parameters to connect hosts to Satellite
set_repositories_satellite_org: org_CHANGEME (secret)
set_repositories_satellite_activationkey: ak_CHANGEME (secret)
set_repositories_satellite_url: url_CHANGEME (secret)
set_repositories_satellite_ha: true
use_content_view: true
set_repositories_satellite_pool: "^Ansible Automation .*"

# Install license from URL
tower_license_manifest:
  type: url
  url: <url to a file to download>
  username: <username to grab the url>
  password: <password to grab the url>

# Cloud specfic settings - example given here for AWS
# Follow those steps to find out the correct parameters:
# 1. Edit `~/.aws/credentials` based on information from sandbox e-mail
#    and enter aws_access_key_id & aws_secret_access_key
# 2. Call `aws route53 list-hosted-zones --query 'HostedZones[*]' --output text`.
#    Note down the first /hostedzone/XYZ123... ID (the one named like the sandbox domain without GUID).
# 3. Call `aws ec2 import-key-pair --key-name id_rsa_xxx --region=us-west-1 --output=text \
#              --public-key-material "$(cat ~/.ssh/id_rsa_xxx.pub)"`.

cloud_provider: ec2                     # Which AgnosticD Cloud Provider to use
aws_region: us-west-1                   # CHANGEME-ec2
HostedZoneId: XYZ123ABX456R6            # CHANGEME-ec2
key_name: id_rsa_xxx                    # CHANGEME-ec2

aws_access_key_id: somethingcomplex               # CHANGEME-ec2
aws_secret_access_key: somethingevenmore complex  # CHANGEME-ec2

key_local_path:
- "~/.ssh/{{key_name}}.pem"

#Ansible Tower related vars

software_to_deploy: none              # Define tower to install tower or none to have only infra ready.
