---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Install Ansible automation controller
  hosts: bastions[0]
  gather_facts: false
  become: true
  tasks:
    - name: Download Manifest for Controller
      get_url:
        url: "{{ controller_manifest.url }}"
        dest: /tmp
        username: "{{ controller_manifest.username }}"
        password: "{{ controller_manifest.password }}"

    - name: Install Ansible automation controller (config role)
      include_role:
        name: deploy_automationcontroller_cfg

    - name: deploy LE CA Certificate files
      copy:
        src: lets-encrypt-r3.pem
        dest: /etc/pki/ca-trust/source/anchors/
        owner: root
        group: root
        mode: 0644

    - name: update CA trusts
      shell: update-ca-trust

    # note that we remove YUM/RPM installed ansible before installing
    # automationcontroller, now we install it back to avoid needing EPEL
    - name: install ansible on the bastion (avoiding EPEL)
      dnf:
        name: ansible
        state: present
        disablerepo: epel

- name: Install license and LE certs on autoctl nodes
  hosts: acs[0]
  gather_facts: false
  become: true
  tasks:
    - name: License autoctl nodes (config role)
      include_role:
        name: tower-license-injector_cfg
      run_once: true

    - name: call issue_cert role (config role)
      include_role:
        name: automation_controller_issue_cert_cfg


- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
