---
- name: Include defaults for ec2
  when:
  - agnosticd_foundation == 'aws_cloud_formation'
  include_role:
    name: architectures/ocp4_cluster
    defaults_from: aws_cloud_formation.yml
    tasks_from: /dev/null
    public: true
