---
# WK: this should no longer be needed here
# - import_playbook: ../include_vars.yml

- name: Run infra-aws-capacity-reservation role
  include_role:
    name: infra-aws-capacity-reservation
  vars:
    ACTION: destroy

- name: Run create_ssh_provision_key role
  include_role:
    name: create_ssh_provision_key

- name: Run infra-ec2-ssh-key destroy role
  include_role:
    name: infra-ec2-ssh-key
  vars:
    ACTION: destroy

- name: Run infra-aws-open-environment role
  when: agnosticd_open_environment | default(false) | bool
  include_role:
    name: infra-aws-open-environment
  vars:
    ACTION: destroy

- name: Run infra-ec2-template-destroy role
  include_role:
    name: infra-ec2-template-destroy
