---
- name: Test that the aws CLI is available
  ansible.builtin.shell: command -v aws
  failed_when: false
  changed_when: false
  check_mode: false
  register: r_aws

- name: Fail if AWS command CLI if not available
  fail:
    msg: AWS command not found in PATH.
  when: r_aws.rc != 0
