---
- name: Generate SSH keys
  command: >-
    ssh-keygen
    -t {{ agnosticd_ssh_key_type | quote }}
    -f {{ agnosticd_ssh_key_path | quote }}
    -q -N ""
  args:
    creates: "{{ agnosticd_ssh_key_path }}"
  register: r_ssh_key_gen

- name: Fix permission of ssh key
  file:
    path: "{{ agnosticd_ssh_key_path }}"
    mode: u=rw,go=

- name: Generate SSH pub key content
  command: >-
    ssh-keygen -y -f {{ agnosticd_ssh_key_path | quote }}
  changed_when: false
  register: r_ssh_provision_pubkey

- name: Set fact for agnosticd_ssh_pubkey_content
  set_fact:
    agnosticd_ssh_pubkey_content: "{{ r_ssh_provision_pubkey.stdout.strip() }}"

- name: Write SSH pub key
  copy:
    content: "{{ agnosticd_ssh_pubkey_content }}"
    dest: "{{ agnosticd_ssh_pubkey_path }}"

- name: Save output dir with generated SSH key
  when: r_ssh_key_gen is changed
  include_role:
    name: agnosticd_save_output_dir
