---
- name: Add localhost explicitly to inventory to appear in group "all"
  ansible.builtin.add_host:
    host: >-
      {% if localhost_host_count > 1 -%}
      localhost-{{ __localhost_host_n }}
      {%- else -%}
      localhost
      {%- endif %}
    ansible_connection: local
  loop: "{{ range(localhost_host_count) | list }}"
  loop_control:
    loop_var: __localhost_host_n
