---
- name: wait for linux host to be available
  ansible.builtin.wait_for_connection:
    timeout: 300
  register: rwait
  ignore_errors: true

- name: restart instance if wait_for_connection failed
  become: false
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    AWS_DEFAULT_REGION: "{{aws_region_final|d(aws_region)}}"
  ansible.builtin.command: "aws ec2 reboot-instances --instance-ids '{{ instance_id }}'"
  delegate_to: localhost
  when: rwait is failed

- name: wait for linux host to be available (retry)
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 200
  when: rwait is failed

- ansible.builtin.ping:
  register: rping
  retries: 3
  delay: 10
  until: rping is succeeded
  tags: must
