---
# Roles to be dynamically installed by AgnosticD before running
# this canvas
roles:
# Setup grader host virtualenv and FTL grading infra
- name: ftl-injector
  src: https://github.com/redhat-gpte-devopsautomation/ftl-injector
  version: v0.17

# Collections to be dynamically installed by AgnosticD before running
# this canvas
collections:
- name: kubernetes.core
  version: 2.3.0
- name: openstack.cloud
  version: 1.8.0
- name: amazon.aws
  version: 2.2.0
  # version: 3.2.0
  # version 3 breaks things because if removes the `*.facts` aliases
- name: community.general
  version: 4.8.0
- name: ansible.posix
  version: 1.3.0
