---
- name: Set hostname based on tag_internaldns
  ansible.builtin.hostname:
    name: "{{ internaldns }}"
  when: internaldns is defined

- ansible.builtin.stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_cfg_file

- name: disable updating hostname in /etc/cloud/cloud.cfg
  when: cloud_cfg_file.stat.exists
  ansible.builtin.lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: 'update_hostname$'
    line: '# - update_hostname'
    backup: true
  tags: disable_cloud_cfg_hostname

- name: Add preserve_hostname to /etc/cloud/cloud.cfg
  when: cloud_cfg_file.stat.exists
  ansible.builtin.lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: '^preserve_hostname'
    line: 'preserve_hostname: true'
    backup: true
  tags: disable_cloud_cfg_hostname
