---
aws_cloud_formation_bastion_name: bastion
aws_cloud_formation_bastion_instance_image: RHEL8-default
aws_cloud_formation_bastion_instance_type: t3a.medium
aws_cloud_formation_bastion_rootfs_size: 30

aws_cloud_formation_instances:
- name: "{{ aws_cloud_formation_bastion_name }}"
  unique: true
  public_dns: true
  image: "{{ aws_cloud_formation_bastion_instance_image }}"
  flavor:
    ec2: "{{ aws_cloud_formation_bastion_instance_type }}"
  tags:
  - key: AnsibleGroup
    value: bastions
  rootfs_size: "{{ aws_cloud_formation_bastion_rootfs_size }}"
  security_groups:
  - BastionSG
