---
- name: Save output dir if archive file is defined
  when: agnosticd_save_output_dir_archive is defined
  block:
  - name: Create output dir archive
    include_tasks:
      file: create-output-dir-archive.yml

  - name: Upload output dir archive to S3
    when: agnosticd_save_output_dir_s3_bucket is defined
    include_tasks:
      file: upload-archive-s3.yml

  always:
  - name: Remove output dir archive tempfile
    when: agnosticd_save_output_dir_archive_tempfile is defined
    file:
      path: "{{ agnosticd_save_output_dir_archive_tempfile }}"
      state: absent

  - name: Remove output dir encrypted archive tempfile
    when: agnosticd_save_output_dir_archive_password is defined
    file:
      path: "{{ agnosticd_save_output_dir_archive_tempfile }}.gpg"
      state: absent
...
