---
- name: Install ansible-galaxy requirements for architecture {{ agnosticd_foundation | default('') }}
  include_tasks:
    file: ansible_galaxy_install_requirements.yml
  vars:
    __ansible_galaxy_requirements_content: "{{ lookup('file', __ansible_galaxy_requirements_path) | from_yaml }}"
    __ansible_galaxy_requirements_path: "{{ __ansible_galaxy_requirements_find[0] }}"
    __ansible_galaxy_requirements_find: >-
      {{
        query('first_found', ['roles/foundations/' ~ agnosticd_foundation ~ '/meta/requirements.yml'], skip=true)
      }}
  when: __ansible_galaxy_requirements_find | length > 0

- name: Install ansible-galaxy requirements for architecture {{ agnosticd_architecture | default('') }}
  include_tasks:
    file: ansible_galaxy_install_requirements.yml
  vars:
    __ansible_galaxy_requirements_content: "{{ lookup('file', __ansible_galaxy_requirements_path) | from_yaml }}"
    __ansible_galaxy_requirements_path: "{{ __ansible_galaxy_requirements_find[0] }}"
    __ansible_galaxy_requirements_find: >-
      {{
        query('first_found', ['roles/architectures/' ~ agnosticd_architecture ~ '/meta/requirements.yml'], skip=true)
      }}
  when:
  - agnosticd_architecture is defined
  - __ansible_galaxy_requirements_find | length > 0

- name: Install ansible-galaxy requirements for workloads
  include_tasks:
    file: ansible_galaxy_install_requirements.yml
  loop: "{{ agnosticd_workloads }}"
  loop_control:
    loop_var: __agnosticd_workload
  vars:
    __ansible_galaxy_requirements_content: "{{ lookup('file', __ansible_galaxy_requirements_path) | from_yaml }}"
    __ansible_galaxy_requirements_path: "{{ __ansible_galaxy_requirements_find[0] }}"
    __ansible_galaxy_requirements_find: >-
      {{
        query('first_found', ['roles/workloads/' ~ __agnosticd_workload.name ~ '/meta/requirements.yml'], skip=true)
      }}
  when: __ansible_galaxy_requirements_find | length > 0
