---
- name: Install ansible-galaxy requirements for foundation
  include_tasks:
    file: ansible_galaxy_install_requirements.yml
  vars:
    __ansible_galaxy_requirements_content: "{{ lookup('file', __ansible_galaxy_requirements_path) | from_yaml }}"
    __ansible_galaxy_requirements_path: "{{ __ansible_galaxy_requirements_find[0] }}"
    __ansible_galaxy_requirements_find: >-
      {{
        query('first_found', ['roles/foundations/' ~ agnosticd_foundation ~ '/meta/requirements.yml'], skip=true, wantlist=false)
      }}
  when: __ansible_galaxy_requirements_find | length > 0
