---
- name: Install roles from {{ __ansible_galaxy_requirements_path }}
  ansible.builtin.command: >-
    ansible-galaxy install
    -r "{{ __ansible_galaxy_requirements_path }}"
    -p "{{ role_path }}/../../dynamic_roles"
  when: >-
    __ansible_galaxy_requirements_content is sequence or (
      __ansible_galaxy_requirements_content is mapping and 'roles' in __ansible_galaxy_requirements_content
    )
  register: r_ansible_galaxy_install_roles
  until: r_ansible_galaxy_install_roles is successful
  retries: 10
  delay: 30

- name: Install collections from {{ __ansible_galaxy_requirements_path }}
  vars:
    __from_ee: "{{ lookup('env', 'LAUNCHED_BY_RUNNER') == '1' }}"
    __collections_path: "{{ lookup('config', 'COLLECTIONS_PATHS')[0] }}"
  ansible.builtin.command: >-
    ansible-galaxy collection install
    -r "{{ __ansible_galaxy_requirements_path }}"
    -p "{{ __collections_path | quote }}"
    --force-with-deps
  when: >-
    __ansible_galaxy_requirements_content is mapping
    and "collections" in __ansible_galaxy_requirements_content
    and (__collections_path.startswith('/tmp/') or  __from_ee | bool)
  register: r_ansible_galaxy_install_collections
  until: r_ansible_galaxy_install_collections is successful
  retries: 10
  delay: 30
