---
- name: Output Directory
  ansible.builtin.import_tasks:
    file: output_dir.yml

- name: Install ansible-galaxy roles and collections
  ansible.builtin.include_tasks:
    file: ansible_galaxy.yml
  when: agnosticd_ansible_galaxy_install_enabled | bool
