---
- name: Create output dir if it does not exists
  file:
    path: "{{ agnosticd_output_dir }}"
    state: directory
  when: not agnosticd_output_dir is exists

- name: Create empty user-info.yaml and user-data.yaml in output dir
  copy:
    content: |
      ---
    dest: "{{ agnosticd_output_dir }}/{{ item }}"
  loop:
  - user-info.yaml
  - user-data.yaml


- name: Attempt to restore output_dir contents
  when: agnosticd_save_output_dir_archive is defined
  include_role:
    name: agnosticd_restore_output_dir
