- name: Create AgnosticD ssh key
  ansible.builtin.include_role:
    name: agnosticd_ssh_key
    tasks_from: create.yml
    public: true

- name: Create key in AWS EC2
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    AWS_REGION: "{{ aws_region }}"
  amazon.aws.ec2_key:
    name: "{{ agnosticd_ssh_key_name }}"
    key_material: "{{ agnosticd_ssh_pubkey_content }}"
