---
- name: Step 004 - Software
  hosts: bastions
  gather_facts: false
  become: true
  environment:
    AWS_DEFAULT_REGION: "{{ aws_region }}"
  tasks:
    - tags:
        - install_awscli
      block:
        - name: Get awscli bundle
          get_url:
            url: https://s3.amazonaws.com/aws-cli/awscli-bundle-1.18.200.zip
            dest: /tmp/awscli-bundle.zip
        - name: Unzip awscli-bundle.zip
          unarchive:
            src: /tmp/awscli-bundle.zip
            dest: /tmp/
            remote_src: true
        - name: Install awscli
          command: /tmp/awscli-bundle/install -i /usr/local/aws -b /bin/aws
          args:
            creates: /usr/local/aws
          become: true
        - name: cleanup archive and tmp files
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/awscli-bundle
            - /tmp/awscli-bundle.zip

    - tags:
        - create_aws_dir
      block:
        - name: Create .aws directory
          file:
            path: ~/.aws
            state: directory

    - tags:
        - create_aws_creds
      block:
        - name: Add aws credentials
          blockinfile:
            path: ~/.aws/credentials
            create: yes
            mode: 0600
            block: |-
              [default]
              aws_access_key_id={{ hostvars.localhost.rosa_access_key_id }}
              aws_secret_access_key={{ hostvars.localhost.rosa_secret_access_key }}
    - tags:
        - create_aws_config
      block:
        - name: Add aws config
          blockinfile:
            path: ~/.aws/config
            create: yes
            mode: 0600
            block: |-
              [default]
              region={{ aws_region }}
    - tags:
        - install_rosacli
      block:
        - name: Get ROSA CLI
          get_url:
            url: "{{ rosa_installer_url }}"
            dest: /tmp/rosa-linux.tar.gz
        - name: Unzip rosa-linux.tar.gz
          unarchive:
            src: /tmp/rosa-linux.tar.gz
            dest: /usr/local/bin/
            remote_src: true
          become: true
        - name: cleanup archive file
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/rosa-linux.tar.gz

    - tags:
        - verify_rosa_installer
      block:
        - set_fact:
            rosa_token: "{{ gpte_rosa_token }}"
          when: rosa_token == ""
        - name: Log into ROSA
          command: "/usr/local/bin/rosa login --token {{ rosa_token }}"
        - name: Init AWS account for ROSA
          command: "/usr/local/bin/rosa init"
        - name: Verify permissions for ROSA
          command: "/usr/local/bin/rosa verify permissions"
        - name: Verify quota for ROSA
          command: "/usr/local/bin/rosa verify quota"

      block:
        - name: Print ROSA admin credentials as user.info
          agnosticd_user_info:
            msg: |
              WARNING: with great power comes great responsibility. We monitor usage.
              Your AWS credentials are:
              AWS_ACCESS_KEY_ID: {{ hostvars.localhost.rosa_access_key_id }}
              AWS_SECRET_ACCESS_KEY: {{ hostvars.localhost.rosa_secret_access_key }}
              ** Please be very careful to not expose AWS credentials in GIT repos or anywhere else that could be public! **
              ** If your credentials are compromised, your environment will be deleted without warning. **
              Your AWS credentials are preconfigured in ~/.aws/credentials on the bastion host.
              AWS Web Console Access: https://{{ sandbox_account_id }}.signin.aws.amazon.com/console
              AWS Web Console Credentials: {{ hostvars.localhost.rosa_console_user_name }} / {{ hostvars.localhost.rosa_console_password }}
              NOTE: The ROSA CLI is preinstalled in /usr/local/bin and should be in your path. There is no need to use sudo or root.
              Your ROSA environment consists of:
              3 m5.2xlarge master nodes
              2 m5.xlarge worker nodes
              2 r5.xlarge infra nodes
              1 t2.small bastion
