---
name: release
on:
  push:
    branches:
      - main
    paths:
      - 'roles/foundations/*/meta/version.yml'
      - 'roles/architectures/*/meta/version.yml'
      - 'roles/implementations/*/meta/version.yml'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Make Release
      run: |
        for RELEASE_FILE in $(
          git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} \
          | grep '^canvas/[^/]+/meta/releases.ya?ml'$)
        ) do
          echo "${RELEASE_FILE}"
          python3 .github/util/release.py "${RELEASE_FILE}"
        done
